config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'main/index'
  root 'main#index'

  resources :todos do
    member do
      patch 'done'
    end
  end
  
  resources :tags do
    member do
      get "tags/tag_form" => 'tags#new', :as => :new
    end
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates_uniqueness_of :name, scope: [:user_id]
    has_many :taggings
    has_many :todos, through: :taggings
    belongs_to :user
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
    # Validation for todo item; must not be empty
    validates :item, presence: true

    # By recommendation of https://github.com/rubocop-hq/rails-style-guide#activerecord use has_many :through instead of 
    # has_and_belongs_to_many, because has_many :through "allows additional attributes and validations on the join model"
    # Hence, decided to use this for future-proofing, should the need arise.
    has_many :taggings
    has_many :tags, through: :taggings
    belongs_to :user

    # def self.tagged_with(id)
    #     Tag.find_by!(id: id).todos
    #     # find_by!(arg, *args) - Finds the first record matching the specified conditions.
    #     #                        No implied ordering. If no record found, raises an ActiveRecord::RecordNotFound error
    # end

    # def self.tag_counts
    #     Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
    #     # select(*fields)
    # end

    # def tag_list
    #     tags.map(&:name).join(', ')
    # end

    # def tag_list=(names)
    #     self.tags = names.split(',').map do |n|
    #         Tag.where(name: n.strip).first_or_create!
    #     end
    # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todos
  has_many :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
    # If logged in, redirect to the user's todos#index
    # redirect_to todos_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @tag = current_user.tags.find(params[:id])
  end

  def edit
    @tag = current_user.tags.all
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.user = current_user
    
    if @tag.save
      redirect_back(fallback_location: todos_path) 
    end
  end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  protect_from_forgery prepend: true, with: :exception
  skip_before_action :verify_authenticity_token, only: :update
  before_action :authenticate_user!

  def new
    @todo = Todo.new
    @tag = Tag.new
  end

  def index 
    #params[:tag] ? @todo = Todo.tagged_with(params[:tag]) : @todo = Todo.all
    @todo = current_user.todos
    @tag = current_user.tags
  end
  
  def show
    @todo = current_user.todos.find(params[:id])
  end

  def create
    # .create is equivalent to .new followed by .save
    # However, .create does not allow us to catch any validation errors
    @todo = Todo.new(todo_params)
    @todo.user = current_user
    

    # .save returns a boolean if saved. Item is saved only if it passes validation
    if @todo.save
      redirect_to @todo
    else
      # If validation failed, run todos#new; passing back the @todo object back into the new template
      render 'new'
    # .create! is a another possible solution. It raises an exception when validation fails
    end

  end

  def edit
    @todo = current_user.todos.find(params[:id])
  end

  def update
     @todo = current_user.todos.find(params[:id])

     if @todo.update(todo_params)
      redirect_to @todo
     else
      render 'edit'
     end
  end

  def destroy
    @todo = current_user.todos.find(params[:id])
    @todo.destroy

    redirect_to todos_path
  end

  def done
    @todo = Todo.find(params[:id])
    if @todo.done == false
      @todo.update_attribute(:done, true)
      redirect_to @todo
    else
      @todo.update_attribute(:done, false)
      redirect_to @todo
    end
  end

  private
    def todo_params
      # strong parameter: forces the item to require fields according to the symbol and allows only the chosen parameters to be passed through
      params.require(:todo).permit(:item, :details, :ddeadline, :tdeadline, :tag, { tag_ids: [] }, :tag_ids)
    end

    # def tag_params
    #   params.require(:tag).permit(:name, :tags)
    # end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%# Note: Not too sure if this is the recommended way to implement. Template defaults for web fonts %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript">
      $(function() {
        var notice = "<%= :notice %>" + " ";
        var alert = "<%= :alert %>" + " ";
        $('#noticeNotif').notify({
          message: { text: notice,
                     type: "success",
                     transition: "fade",
                     delay: 5000,
                     fadeOut: {enabled: true}}
          }, {
            delay: 5000,
            timer: 1000
          }).show();
        $('#alert').notify({
          message: { text: alert,
                     type: "danger",
                     transition: "fade",
                     delay: 5000,
                     fadeOut: {enabled: true}
          }, {
            delay: 5000,
            timer: 1000
          }).show();
      });
    </script>
  </head>

  <body>

  
    <%= yield %>
    <% if notice %>
      <div class="notifications bottom-right" id="noticeNotif"></div>
    <% end %>
    <% if alert %>
      <div class="notifications bottom-right" id="alertNotif"></div>
    <% end %>
  </body>
</html>

app/views/main/index.html.erb
<%# Landing Page%>

<%# Navigation bar%>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="#">LetsDoThis</a>
    <%# Responsive navbar toggler%>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon">
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
        <a class="nav-link" href="mailto:e0310959@u.nus.edu">Contact</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="https://github.com/firzanarmani/TodoApplication">Github</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<%# Header %>
<header class="masthead" style="margin-top:60px;">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">LetsDoThis</div>
      <div class="intro-heading">The to-do app you're probably going to need</div>
      <% if user_signed_in? %>
        <div class="entry-text">Logged in as <b><%= current_user.email %></b></div>
        <br>
        <%= link_to  "Enter", todos_path, :class => 'btn btn-primary btn-xl' %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-primary btn-xl' %>
      <% else %>
        <div class="entry-text"><strong><br><br></strong></div>
        <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-primary btn-xl' %>
        <%= link_to "Login", new_user_session_path, :class => 'btn btn-primary btn-xl' %>
      <% end %>
    </div>
  </div>
  <a style="position:relative;top:35vh;background-color:black;opacity:0.5;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px" href="https://unsplash.com/@glenncarstenspeters?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge" target="_blank" rel="noopener noreferrer" title="Download free do whatever you want high-resolution photos from Glenn Carstens-Peters"><span style="display:inline-block;padding:2px 3px"><svg xmlns="http://www.w3.org/2000/svg" style="height:12px;width:auto;position:relative;vertical-align:middle;top:-2px;fill:white" viewBox="0 0 32 32"><title>unsplash-logo</title><path d="M10 9V0h12v9H10zm12 5h10v18H0V14h10v9h12v-9z"></path></svg></span><span style="display:inline-block;padding:2px 3px">Photo by: Glenn Carstens-Peters</span></a>
</header>

<section class="bg-light" id="team">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">Project Staff</h2>
            <br>
        </div>
      </div>

          <div class="team-member text-center">
            <img class="mx-auto rounded-circle" src="<%= asset_path 'firzan.jpg' %>" alt="">
            <br>
            <br>
            <h4>Firzan Armani</h4>
            <p class="text-muted">Developer</p>
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="https://github.com/firzanarmani/TodoApplication">
                  <i class="fa fa-github fa-2x"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="mailto:e0310959@u.nus.edu">
                  <i class="fa fa-envelope fa-2x"></i>
                </a>
              </li>
            </ul>
          </div>

        
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <p class="large text-muted">An aspiring self-taught front-end and back-end developer hungry to innovate and make change!</p>
          </div>
        </div>
      </div>
    </div>
</section>

app/views/tags/_tag_form.html.erb
<script type="text/javascript">
$(document).on('ajax:success'), function() {
  $('#.chosen-select').trigger("chosen:updated");
}
</script>

<%= form_with(model: @tag, local: true) do |formTag| %>
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalTitle">Add new tag</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
        <%= formTag.label "Tag name", class: "control-label"%>
        <%= formTag.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= formTag.submit 'Add', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/tags/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-11 col-md-9 col-lg-7 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <div>
            <%= link_to "", todos_path, {class: "fa fa-arrow-left", style:"margin-top:10px;position:relative;float:left"} %>
            <h4 class="card-title text-center">
              Items tagged with:
              <br>
              <b><%= @tag.name %></b>
            </h4>
          </div>

          <div>
            <% @tag.todos.each do |todo| %>
              <%= link_to todo.item, todo_path(todo) %>
              <br>
              <small><%= todo.details %></small>
            <% end %>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/todos/_todo_form.html.erb
<script type="text/javascript">
$(function() {
    $(".chosen-select").chosen({
      allow_single_deselect: true,
      no_results_text: 'No results matched',
      width: '250px',
      });
    $("#deadlineCheck").change(function() {
      if(this.checked !=true) {
        $("#deadlinePicker").hide();
        $("#alldayGroup").hide();
      } else {
        $("#deadlinePicker").show();
        $("#alldayGroup").show();
      }
    });
    $("#deadlineCheck").ready(function() {
      if(<%= @todo.tdeadline.nil? and @todo.ddeadline.nil? %>) {
        $("#deadlinePicker").hide();
        $("#alldayGroup").hide();
        $("#deadlineCheck").prop('checked', false);
      } else {
        $("#deadlinePicker").show();
        $("#alldayGroup").show();
        $("#deadlineCheck").prop('checked', true);
      }
    });
    $("#alldayCheck").change(function() {
      if(this.checked !=true) {
        $("#timePicker").show();
      } else {
        $("#timePicker").hide();
      }
    });
    $("#alldayCheck").ready(function() {
      if(<%= @todo.tdeadline.nil?%>) {
        $("#timePicker").hide();
        $("#alldayCheck").prop('checked', true);
      } else {
        $("#timePicker").show();
        $("#alldayCheck").prop('checked', false);
      }
    });
});
</script>
<%# model: @object takes in an object that has been passed in and fills up the fields with its values %>
<%= form_with(model: @todo, local: true) do |form| %>
  <%# %>
  <div class = "form-group<%= ' has-error' if @todo.errors.has_key?(:item) %> ">
    <%= form.label :item, class: "control-label" %>
    <%= form.text_field :item, class: "form-control", placeholder: "What needs to be done?" %>
    <% @todo.errors.full_messages_for(:item).each do |message| %>
      <p style="font-size:13px;color:red;margin-left:13px;">*<%= message %></p>
    <% end %>
  </div>

  <div class = "form-group">
    <%= form.label :details %>
    <%= form.text_area :details, { class: "form-control", style: "resize:none;" } %>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-6">
      <%= form.label "Deadline" %>
        <input class="form-check-input" style="right:16px;" type="checkbox" value="" id="deadlineCheck">
      </div>
      <div class="col-6" id="alldayGroup" style="display:none;">
        <%= form.label "All day", class:"control-label" %>
        <input class="form-check-input" style="right:16px;" type="checkbox" value="" id="alldayCheck">
      </div>
    </div>
    <div class="row form-group" style="display:none;" id="deadlinePicker">
      <div class="col">
        <%= form.date_field :ddeadline, class: "form-control" %>
      </div>
      <div class="col">
        <div id="timePicker" style="display:none">
          <%= form.time_field :tdeadline, class: "form-control"%>
        </div>
      </div>
    </div>
  </div>

  <div class = "form-group">
    <%#= link_to  "New Tag", model %>
    <%= form.label :tags %>
    <br>
    <%= form.select :tag_ids, Tag.all.map { |t| [t.name, t.id] }, { include_blank: true }, { multiple: true, class: "chosen-select", data: { placeholder: "Choose from existing tags"} } %>
    <button type="button" id="addTagBtn" class="btn btn-primary" data-toggle="modal" data-target=#tagModal>Add new tag</button>
    <%# select (name) (id) (options) - name has already been declared as the scope of the form helper, options is an collection of array of name and id/number of each option%>
    <%# collect method invokes a block of code for each element of self. In this case, for each item 't' create an array of its name and id, exactly the same as the map function%>
  </div>

  <hr class="my-4">
  <div class="row form-group">
    <div class="col-6">
      <%= link_to 'Cancel', cancel_url, class: 'btn btn-secondary' %>
    </div>
    <div class="col-6">
      <%= form.submit 'Save', { class: 'btn btn-primary', style: "position:absolute;right:0px;" } %>
    </div>
  </div>
<% end %>

<div class="modal" id="tagModal" tabindex="-1" role="dialog">
  <%= render partial:"tags/tag_form" %>
</div>

app/views/todos/_todo_form.js.erb
$function(){
        $('#.chosen-select').empty(); //remove all child nodes
        $('#.chosen-select').trigger("chosen:updated");
    });

app/views/todos/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-11 col-md-9 col-lg-7 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h4 class="card-title text-center">Change a To-do</h4>
            <%= render partial: "todo_form", locals: { cancel_url: todo_path(@todo) } %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/todos/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-11 col-md-9 col-lg-7 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h4 class="card-title text-center">My To-dos</h4>

          <div class="container">
          <p>
            <% @todo.each do |todo| %>
              <h2>
              <%= link_to todo.item, todo_path(todo) %>
              <% if todo.done %>
              <div class= "fa fa-check-square fa-1x" style= "position:relative;float:right;margin-top:5px;color:#fec503"/>
              <% else %>
              <div class= "fa fa-square-o fa-1x" style= "position:relative;float:right;margin-top:5px;color:#fec503"/>
              <% end %>
              </h2>
            <% end %>
          </p>
          <br>
          <br>
          All tags:
          <p>
            <% @tag.each do |tag| %>
              <%= link_to tag.name, tag_path(tag) %></h2>
            <% end %>
          </p>
          <br>
          <p>
          <%#Completed to-dos%>
          <%# Toggle to show completed todos%>
          </p>
          <p>
            <%= link_to  "Create new to-do", new_todo_path, class:"btn btn-primary", style:"position:relative;float:right"%>
          </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-11 col-md-9 col-lg-7 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h4 class="card-title text-center">Add a To-do</h4>
            <%= render partial: "todo_form", locals:{ cancel_url: todos_path} %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/todos/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-11 col-md-9 col-lg-7 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <div >
              <%= link_to "", todos_path, {class: "fa fa-arrow-left", style:"margin-top:10px;position:relative;float:left"} %>
              <%= @todo.done ? (link_to "", done_todo_path(@todo), remote: true, method: :patch, data: {confirm: 'Mark as not done?'}, class: "fa fa-check-square fa-2x" , style: "position:relative;float:right;margin-top:3px")
                             : (link_to "", done_todo_path(@todo), remote: true, method: :patch, data: {confirm: 'Mark as done?'}, class: "fa fa-square-o fa-2x", style: "position:relative;float:right;margin-top:3px") %>
              <h4 class="card-title text-center"><%= @todo.item %></h4>
          </div>
          <div>
            <%= @todo.details %>
            <br>
          </div>

          <div>
            <small>
              Tags: 
              <% @todo.tags.each do |tag| %>
                <%= link_to tag.name, tag_path(tag) %>
              <% end %>
            </small>
          </div>
          <hr class="my-4">
          <div class="form-group">
            <%= link_to  "Delete", todo_path(@todo), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-secondary", style:"margin-left:0px" %>
            <%= link_to  "Edit", edit_todo_path(@todo), class: "btn btn-primary", style: "position:relative;float:right" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>